##
# (c) 2021 - Cloud Ops Works LLC - https://cloudops.works/
#            On GitHub: https://github.com/cloudopsworks
#            Distributed Under Apache v2.0 License
#
name: Environment Auto Merge on Pull request
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled
      - edited
    paths-ignore:
      - ".github/workflows/**"
      - "modules/**"
      - ".beacon"
      - ".destroy"

permissions:
  contents: write
  packages: read
  statuses: write
  pull-requests: write
  issues: write
  checks: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: pascalgn/automerge-action@v0.15.2
        if: ${{ startsWith(github.head_ref, 'promote-') }}
        env:
          GITHUB_TOKEN: "${{ secrets.BOT_TOKEN }}"
          MERGE_LABELS: "approved,!do-not-merge"
          UPDATE_LABELS: "approved"
          LOG: "TRACE"
      - uses: actions/github-script@v4
        if: ${{ ! startsWith(github.head_ref, 'promote-') }}
        with:
          github-token: ${{ secrets.BOT_TOKEN }}
          script: |
            const {data: pullLabels} = await github.issues.listLabelsOnIssue({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            const labels = pullLabels.map(label => label.name);

            var is_mergeable = false;

            for (const aLabel of labels) {
              if ( aLabel == 'approved' ) {
                is_mergeable = true;
              }
            }

            if ( is_mergeable ) {
              github.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                merge_method: 'merge'
              });
            }
